config/routes.rb
Rails.application.routes.draw do
  
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  post '/articles', to: 'articles#create'
  devise_for :users
  #resources :users
  root to: "home#welcome"
  get '/orders', to: 'orders#index'
  post '/orders/submit', to: 'orders#submit'

  get '/cart', to: 'cart#index'
  post '/cart/purchased', to: 'cart#purchased' 

  get '/checkout', to: 'checkout#order' 
  get '/checkout/secret', to: 'checkout#secret' 
  get '/checkout/confirm', to: 'checkout#confirm' 
  
  
  post '/create-payment-intent', to: 'checkout#secret'
  get '/confirm-payment-intent', to: 'checkout#confirm'  
  post '/confirm-payment-intent', to: 'checkout#confirm' 
  
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def index
        @products = Product.all
    end

    def purchased
        #byebug
        #prepare_new_order
        @product_price = purchase_params[:price]
        @product_name = purchase_params[:order_number]
        token = purchase_params[:token]
        Stripe.api_key = Rails.application.credentials.stripe[:STRIPE_TEST_SECRET_KEY]
        pi = Stripe::PaymentIntent.create({amount: @product_price, currency: 'usd', payment_method_types: ['card']})
        Stripe::PaymentIntent.confirm(pi.id, {payment_method: 'pm_card_visa'})
        @mostrar = pi.id
    end

    def secret
        @pi = Stripe::PaymentIntent.create({amount: 1000, currency: 'usd', payment_method_types: ['card']})
        render json: @pi      
    end

    def confirm
        #byebug
        @id = params[:orders][:token]
        @confirm = Stripe::PaymentIntent.confirm(@id, {payment_method: 'pm_card_visa'})
        render json: @confirm
    end


    private

    def prepare_new_order
        @order = Order.new(order_params)
        @order.user_id = current_user.id
        @product = Product.find(@order.product_id)
        @order.price_cents = @product.price_cents
        @order.token = order_params[:token]
      end
    def purchase_params
        params.require(:orders).permit(:order_number, :token, :price, :card_number, :card_expiration_month, :card_expiration_year, :card_expiration_year, :card_cvc)
    end
end

app/views/cart/index.html.erb
<%= stripe_javascript_tag %>


<h1>Checkout</h1>
<h3>Your cart: </h3>
<%= form_with url: "/cart/purchased", method: :post, id:"order-details"  do |form| %>
    <ul>
        <%= form.label 'Order number'%>
        <%= form.text_field 'orders[order_number]', id:"product_name", value: "Orden 1000" %><br>
        <%= form.label 'Total price'%>
        <%= form.number_field 'orders[price]', id:"product_amount", value: 5000 %><br>
        
    </ul>
    <div id= 'card-element'></div>
    <div id = 'card-errors', role="alert"></div>
    <%= form.submit 'Buy it!', id: "submit-stripe"%>
<% end %>



<%= javascript_pack_tag 'carrito'%>
<%= tag :meta, :name => "stripe-key", :content => Rails.application.credentials.stripe[:STRIPE_TEST_PUBLISHABLE_KEY] %>

app/views/cart/purchased.html.erb
<%= @mostrar %>

<%= link_to 'Comprar', cart_path %>