config/routes.rb
Rails.application.routes.draw do
  
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  post '/articles', to: 'articles#create'
  devise_for :users
  #resources :users
  root to: "home#welcome"
  get '/orders', to: 'orders#index'
  post '/orders/submit', to: 'orders#submit'

  get '/cart', to: 'cart#index'
  post '/cart/purchased', to: 'cart#purchased' 

  get '/checkout', to: 'checkout#order' 
  get '/checkout/secret', to: 'checkout#secret' 
  get '/checkout/confirm', to: 'checkout#confirm' 
  
  
  post '/create-payment-intent', to: 'checkout#secret'
  get '/confirm-payment-intent', to: 'checkout#confirm'  
  post '/confirm-payment-intent', to: 'checkout#confirm' 
  
  
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def order
        #byebug
        @order_number = 'ORD1000'
        @total_price = 5000
        @current_user = current_user.email
        Stripe.api_key = Rails.application.credentials.stripe[:STRIPE_TEST_SECRET_KEY]
        
        
       
    end

    def secret
        @total_price = 5000
        @pi = Stripe::PaymentIntent.create({amount: @total_price, currency: 'usd', automatic_payment_methods: {enabled: true}})
        render json: @pi      
    end

    def confirm
        #byebug
        @order_number = 'ORD1000'
        @total_price = 5000
        @current_user = current_user.email
        @pi = params[:payment_intent_client_secret]
        @pi_client_secret = params[:payment_intent_client_secret]
        if params[:redirect_status] == 'requires_payment_method'
            render 'http://localhost:3000/checkout'    
        else 
            @status = params[:redirect_status]
        end
    end

    private


end

app/views/checkout/confirm.html.erb
<script src="https://js.stripe.com/v3/"></script>

<% if  @status == "succeeded"%>
    Confirm:
    <p> User email: <%= @current_user %> </p>
    <p> Order number: <%= @order_number %> </p>
    <p> Total price: <%= @total_price %> </p>
    <div id="message"> </div>
<% else %>
    There were a problem with your payment!
    <div id="message"> </div>
<% end %>

<%= tag :meta, :name => "stripe-key", :content => Rails.application.credentials.stripe[:STRIPE_TEST_PUBLISHABLE_KEY] %>
<%= javascript_pack_tag 'status'%>

<%= link_to 'Keep purchasing', checkout_path%>

app/views/checkout/order.html.erb
<script src="https://js.stripe.com/v3/"></script>


<h1> Checkout </h1>
    <p> User email: <%= @current_user %> </p>
    <p> Order number: <%= @order_number %> </p>
    <p> Total price: <%= @total_price %> </p>

  
<%= form_with url: "/confirm-payment-intent", method: :post, id:"payment-form"  do |form| %>
        <div id="payment-element">
                <!--Stripe.js injects the Payment Element-->
        </div>
        <div id = 'card-errors', role="alert"></div>
        <%= form.submit 'Pay now', id: "submit" %>
        <div id="payment-message" class="hidden"></div>
<% end %>

<%= tag :meta, :name => "stripe-key", :content => Rails.application.credentials.stripe[:STRIPE_TEST_PUBLISHABLE_KEY] %>


<%= link_to 'Orders', orders_path %>

<%= javascript_pack_tag 'checkout'%>