config/routes.rb
Rails.application.routes.draw do
  
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  post '/articles', to: 'articles#create'
  devise_for :users
  #resources :users
  root to: "home#welcome"
  get '/orders', to: 'orders#index'
  post '/orders/submit', to: 'orders#submit'

  get '/cart', to: 'cart#index'
  post '/cart/purchased', to: 'cart#purchased' 

  get '/checkout', to: 'checkout#order' 
  get '/checkout/secret', to: 'checkout#secret' 
  get '/checkout/confirm', to: 'checkout#confirm' 
  
  
  post '/create-payment-intent', to: 'checkout#secret'
  get '/confirm-payment-intent', to: 'checkout#confirm'  
  post '/confirm-payment-intent', to: 'checkout#confirm' 
  
  
end

app/models/article.rb
class Article < ApplicationRecord

    attr_accessor :card_number, :card_expiration_month, :card_expiration_year, :card_cvc
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    #byebug
    @article = Orders::ArticlesCreator.new(params[:article][:title], params[:article][:body]).create
    if @article.save
      redirect_to 'articles/index'
    else
        render 'articles/new'
    end
  end

  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>
<% @articles.each do |article|%>
<ul>
    <li> <%= article.title%> - <%= article.body%> </li>
</ul>
<% end %>
<br>
<%= link_to 'New article', articles_new_path%>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

<%= form_with model: @article do |form| %>
    <%= form.text_field :title %><br>
    <%= form.text_area :body, size: "60x10" %><br>
    <%= form.submit %>
<% end%>